export interface Event {
	category: string
	event: string
	round: string
	venue: string
	startTime: string
	endTime: string
}

export const EventsByDate: { [date: string]: Event[] } = {
	"09 March": [
		{
			category: "Gaming and Workshops",
			event: "Valorant",
			round: "1 of 1",
			venue: "Online",
			startTime: "2:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "COD",
			round: "1 of 1",
			venue: "Online",
			startTime: "2:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Competitive Geoguesser",
			round: "1 of 1",
			venue: "AB3 303",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Bottle Painting Workshop",
			round: "1 of 1",
			venue: "AB5 Entry Foyer",
			startTime: "4:00 pm",
			endTime: "7:00 pm",
		},
	],
	"10 March": [
		{
			category: "Gaming and Workshops",
			event: "Candle Making",
			round: "1 of 1",
			venue: "AB3 204",
			startTime: "5:30 pm",
			endTime: "8:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Improv Comedy",
			round: "1 of 1",
			venue: "AB3 303",
			startTime: "5:30 pm",
			endTime: "8:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Kannada Workshop",
			round: "1 of 1",
			venue: "AB3 304",
			startTime: "5:30 pm",
			endTime: "8:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Crocheting workshop",
			round: "1 of 1",
			venue: "AB3 203",
			startTime: "6:00 pm",
			endTime: "8:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Childhood Games",
			round: "1 of 1",
			venue: "Student Plaza",
			startTime: "5:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Brawl Stars",
			round: "1 of 1",
			venue: "Online",
			startTime: "2:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Marvel Rivals",
			round: "1 of 1",
			venue: "Online",
			startTime: "2:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "OPS & HRD",
			event: "Beast Games",
			round: "7 of 7",
			venue: "AB3",
			startTime: "5:00 pm",
			endTime: "9:30 pm",
		},
	],
	"12 March": [
		{
			category: "Footloose",
			event: "Group Dance Eastern",
			round: "1 of 1",
			venue: "AB1 Quadrangle",
			startTime: "3:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Footloose",
			event: "Street Dance Battle",
			round: "1 of 3",
			venue: "Student Plaza",
			startTime: "1:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Footloose",
			event: "Street Dance Battle",
			round: "2 of 3",
			venue: "Student Plaza",
			startTime: "1:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Footloose",
			event: "Street Dance Battle",
			round: "3 of 3",
			venue: "Student Plaza",
			startTime: "1:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Crescendo",
			event: "NOTA (Creative Jam)",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Iridescent",
			event: "Jeopardy",
			round: "1 of 3",
			venue: "AB5 206, 205",
			startTime: "1:00 pm",
			endTime: "2:00 pm",
		},
		{
			category: "Iridescent",
			event: "Dead Poets Society (English Poetry)",
			round: "1 of 2",
			venue: "AB5 207",
			startTime: "2:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Haute Couture",
			event: "Mr. and Ms. Revels: The Fashion Edition",
			round: "1 of 2",
			venue: "AB3 204",
			startTime: "1:00 pm",
			endTime: "2:30 pm",
		},
		{
			category: "Haute Couture",
			event: "Mr. and Ms. Revels: The Fashion Edition",
			round: "2 of 2",
			venue: "AB5 Foyer",
			startTime: "3:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Haute Couture",
			event: "Brush and Blend (Makeup Competition)",
			round: "1 of 2",
			venue: "AB3 403",
			startTime: "1:00 pm",
			endTime: "2:15 pm",
		},
		{
			category: "Haute Couture",
			event: "Brush and Blend (Makeup Competition)",
			round: "2 of 2",
			venue: "AB3 403",
			startTime: "3:00 pm",
			endTime: "3:30 pm",
		},
		{
			category: "Xventure",
			event: "Hurdle Haven (Obstacle Course)",
			round: "1 of 2",
			venue: "NCC Ground",
			startTime: "3:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Anubhuti",
			event: "Lehza (Hindi Poetry Event)",
			round: "1 of 2",
			venue: "KEF Centre Auditorium",
			startTime: "1:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Anubhuti",
			event: "Antakshari",
			round: "1 of 2",
			venue: "AB3 303",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Anubhuti",
			event: "Antakshari",
			round: "2 of 2",
			venue: "AB3 303",
			startTime: "3:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Lensation",
			event: "Photo Expo",
			round: "1 of 3",
			venue: "AB3 Ramp",
			startTime: "1:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Ergo",
			event: "General Quiz",
			round: "1 of 2",
			venue: "Sir MV Seminar Hall",
			startTime: "1:00 pm",
			endTime: "3:30 pm",
		},
		{
			category: "Ergo",
			event: "General Quiz",
			round: "2 of 2",
			venue: "Sir MV Seminar Hall",
			startTime: "3:30 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Animania",
			event: "Chunin Exams",
			round: "1 of 3",
			venue: "AB3 203",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Kalakriti",
			event: "Anime Art Competition",
			round: "1 of 1",
			venue: "AB3 202",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Dramebaaz",
			event: "Mad Ads",
			round: "1 of 1",
			venue: "AB3 204",
			startTime: "1:00 pm",
			endTime: "2:00 pm",
		},
		{
			category: "Dramebaaz",
			event: "Charades (Mime)",
			round: "1 of 1",
			venue: "AB3 204",
			startTime: "3:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "COD",
			round: "2 of 2",
			venue: "AB5 305",
			startTime: "2:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Brawl Stars",
			round: "2 of 2",
			venue: "AB5 307",
			startTime: "2:00 pm",
			endTime: "4:30 pm",
		},
	],
	"13 March": [
		{
			category: "Footloose",
			event: "Solo Western",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Footloose",
			event: "Solo Eastern",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "3:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Footloose",
			event: "Solo classical",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "5:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Crescendo",
			event: "Silence of the Amps (Acoustic Duet Event)",
			round: "1 of 1",
			venue: "AB3 Stage",
			startTime: "2:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Crescendo",
			event: "Solo Sannata (Solo Instrumental)",
			round: "1 of 2",
			venue: "KC Stage",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Crescendo",
			event: "Solo Sannata (Solo Instrumental)",
			round: "2 of 2",
			venue: "KC Stage",
			startTime: "4:00 pm",
			endTime: "6:30 pm",
		},
		{
			category: "Iridescent",
			event: "Jeopardy",
			round: "2 of 3",
			venue: "AB5 203, 204, 205",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Iridescent",
			event: "Netflix and No Chill (Trivia)",
			round: "1 of 3",
			venue: "AB5 206, 202",
			startTime: "3:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Iridescent",
			event: "Dead Poets Society (English Poetry)",
			round: "2 of 2",
			venue: "AB5 207",
			startTime: "3:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Iridescent",
			event: "Off the Cuff (Extempore)",
			round: "1 of 3",
			venue: "AB5 208",
			startTime: "5:30 pm",
			endTime: "6:30 pm",
		},
		{
			category: "Haute Couture",
			event: "The Fashion Frontier",
			round: "1 of 2",
			venue: "AB1 Quadrangle",
			startTime: "5:00 pm",
			endTime: "9:30 pm",
		},
		{
			category: "Haute Couture",
			event: "The Fashion Frontier",
			round: "2 of 2",
			venue: "AB1 Quadrangle",
			startTime: "5:00 pm",
			endTime: "9:30 pm",
		},
		{
			category: "Xventure",
			event: "Hurdle Haven (Obstacle Course)",
			round: "2 of 2",
			venue: "NCC Ground",
			startTime: "4:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Xventure",
			event: "Trail and Tail(Treasure Hunt)",
			round: "1 of 2",
			venue: "AB3 303, 403",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Anubhuti",
			event: "Tark-Vitark (Hindi Debate Event)",
			round: "1 of 2",
			venue: "AB3 305, 304",
			startTime: "2:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Lensation",
			event: "Photo Expo",
			round: "2 of 3",
			venue: "AB3 Ramp",
			startTime: "1:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Lensation",
			event: "Product Photography",
			round: "1 of 1",
			venue: "AB3 405, 404",
			startTime: "2:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Ergo",
			event: "Debate Tournament",
			round: "1 of 3",
			venue: "AB5 209, 210",
			startTime: "4:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Ergo",
			event: "Themed Quiz",
			round: "1 of 2",
			venue: "Sir MV Seminar Hall",
			startTime: "1:00 pm",
			endTime: "3:30 pm",
		},
		{
			category: "Ergo",
			event: "Themed Quiz",
			round: "2 of 2",
			venue: "Sir MV Seminar Hall",
			startTime: "4:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Animania",
			event: "Chunin Exams",
			round: "2 of 3",
			venue: "AB3 203",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Animania",
			event: "Squid Games",
			round: "1 of 2",
			venue: "Student Plaza",
			startTime: "3:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Kalakriti",
			event: "Painting",
			round: "1 of 1",
			venue: "AB3 403",
			startTime: "2:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Kalakriti",
			event: "Collage Making",
			round: "1 of 1",
			venue: "AB3 202",
			startTime: "4:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Kalakriti",
			event: "Alpana(Rangoli)",
			round: "1 of 1",
			venue: "AB5 Entry Foyer",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Dramebaaz",
			event: "Spotlight(Mimicry)",
			round: "1 of 1",
			venue: "AB3 204",
			startTime: "3:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Valorant",
			round: "2 of 2",
			venue: "AB5 305",
			startTime: "2:00 pm",
			endTime: "4:30 pm",
		},
	],
	"14 March": [
		{
			category: "Footloose",
			event: "Group Dance Western",
			round: "1 of 1",
			venue: "AB1 Quadrangle",
			startTime: "7:00 pm",
			endTime: "9:30 pm",
		},
		{
			category: "Crescendo",
			event: "Swar Sangam (Indian Classical Vocal Group)",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "1:00 pm",
			endTime: "2:30 pm",
		},
		{
			category: "Crescendo",
			event: "Guardians of the Harmony (Western Vocal Group)",
			round: "1 of 1",
			venue: "Library Auditorium",
			startTime: "2:30 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Crescendo",
			event: "Band-ish Bandits (Battle of the Bands)",
			round: "2 of 2",
			venue: "AB1 Quadrangle",
			startTime: "4:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Iridescent",
			event: "Jeopardy",
			round: "3 of 3",
			venue: "AB5 206",
			startTime: "1:00 pm",
			endTime: "3:00 pm",
		},
		{
			category: "Iridescent",
			event: "Netflix and No Chill (Trivia)",
			round: "2 of 3",
			venue: "AB5 207",
			startTime: "3:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Iridescent",
			event: "Off the Cuff (Extempore)",
			round: "2 of 3",
			venue: "AB5 208",
			startTime: "3:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Xventure",
			event: "Trail and Tail (Treasure Hunt)",
			round: "2 of 2",
			venue: "AB3 403",
			startTime: "1:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Xventure",
			event: "Manipal's Got Latent",
			round: "1 of 1",
			venue: "Sir MV Seminar Hall",
			startTime: "4:00 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Anubhuti",
			event: "Tark-Vitark (Hindi Debate Event)",
			round: "2 of 2",
			venue: "AB3 303, 302",
			startTime: "2:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Lensation",
			event: "Photo Expo",
			round: "3 of 3",
			venue: "AB3 Ramp",
			startTime: "2:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Lensation",
			event: "Short Film ",
			round: "Screening",
			venue: "KEF Centre Auditorium",
			startTime: "1:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Ergo",
			event: "Just A Minute (JAM)",
			round: "1 of 2",
			venue: "AB3 404, 405",
			startTime: "2:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Ergo",
			event: "Just A Minute (JAM)",
			round: "2 of 2",
			venue: "AB3 404, 406",
			startTime: "4:00 pm",
			endTime: "5:30 pm",
		},
		{
			category: "Ergo",
			event: "Debate Tournament",
			round: "2 of 3",
			venue: "AB3 202, 205, 304, 305",
			startTime: "5:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Ergo",
			event: "Debate Tournament",
			round: "3 of 3",
			venue: "AB3 202, 205, 304, 306",
			startTime: "5:00 pm",
			endTime: "7:00 pm",
		},
		{
			category: "Animania",
			event: "Chunin Exams",
			round: "3 of 3",
			venue: "AB3 203",
			startTime: "4:30 pm",
			endTime: "6:30 pm",
		},
		{
			category: "Animania",
			event: "Squid Games",
			round: "2 of 2",
			venue: "Student Plaza",
			startTime: "2:00 pm",
			endTime: "4:00 pm",
		},
		{
			category: "Kalakriti",
			event: "Installation Art",
			round: "1 of 1",
			venue: "AB3 204",
			startTime: "3:00 pm",
			endTime: "5:00 pm",
		},
		{
			category: "Dramebaaz",
			event: "Nukkad Natak (Street Play)",
			round: "1 of 1",
			venue: "In Front of AB3",
			startTime: "4:30 pm",
			endTime: "6:00 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Marvel Rivals",
			round: "2 of 2",
			venue: "AB5 305",
			startTime: "2:00 pm",
			endTime: "4:30 pm",
		},
		{
			category: "Gaming and Workshops",
			event: "Competitive Geoguesser",
			round: "2 of 2",
			venue: "AB5 307",
			startTime: "2:00 pm",
			endTime: "4:30 pm",
		},
	],
	"15 March": [
		{
			category: "Crescendo",
			event: "Sing-Hum (Indian Classical Vocals Solo)",
			round: "1 of 1",
			venue: "AB1 Quadrangle",
			startTime: "9:00 am",
			endTime: "12:00 pm",
		},
		{
			category: "Crescendo",
			event: "The Voice (Western Vocals Solo)",
			round: "1 of 1",
			venue: "AB1 Quadrangle",
			startTime: "12:00 am",
			endTime: "2:00 pm",
		},
		{
			category: "Iridescent",
			event: "Off the Cuff (Extempore)",
			round: "3 of 3",
			venue: "AB5 208",
			startTime: "10:00 am",
			endTime: "12:00 pm",
		},
		{
			category: "Iridescent",
			event: "Netflix and No Chill (Trivia)",
			round: "3 of 3",
			venue: "AB5 207",
			startTime: "10:00 am",
			endTime: "12:00 pm",
		},
		{
			category: "Anubhuti",
			event: "Lehza (Hindi Poetry Event)",
			round: "2 of 2",
			venue: "Sir MV Seminar Hall",
			startTime: "10:00 am",
			endTime: "12:00 pm",
		},
	],
}
